# Generated by Django 5.0 on 2024-01-26 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patient", "0003_alter_patientobservation_observation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NortonScale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "physical_condition",
                    models.CharField(
                        choices=[
                            ("4", "Good"),
                            ("3", "Fair"),
                            ("2", "Poor"),
                            ("1", "Very Bad"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mental_condition",
                    models.CharField(
                        choices=[
                            ("4", "Alert"),
                            ("3", "Apathetic"),
                            ("2", "Confused"),
                            ("1", "Stuporous"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("4", "Ambulant"),
                            ("3", "Walks with help"),
                            ("2", "Chairbound"),
                            ("1", "Bedridden"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mobility",
                    models.CharField(
                        choices=[
                            ("4", "Full"),
                            ("3", "Slightly impared"),
                            ("2", "Very limited"),
                            ("1", "Immobile"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "incontinence",
                    models.CharField(
                        choices=[
                            ("4", "None"),
                            ("3", "Occasional"),
                            ("2", "Usually urinary"),
                            ("1", "Urinary and fecal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_points", models.IntegerField(blank=True, null=True)),
                (
                    "pressure_risk",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="norton",
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
