# Generated by Django 5.0 on 2024-01-27 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_alter_patientobservation_observation"),
        ("scales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlasgowComaScale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "eye_response",
                    models.CharField(
                        choices=[
                            ("4", "Eyes open spontaneously"),
                            ("3", "Eye opening to sound"),
                            ("2", "Eye opening to pain"),
                            ("1", "No eye opening"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "verbal_response",
                    models.CharField(
                        choices=[
                            ("5", "Orientated"),
                            ("4", "Confused"),
                            ("3", "Inappropriate words"),
                            ("2", "Incomprehensible sounds"),
                            ("1", "No verbal response"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "motor_response",
                    models.CharField(
                        choices=[
                            ("6", "Obeys commands"),
                            ("5", "Localizing pain"),
                            ("4", "Withdrawal from pain"),
                            ("3", "Abnormal flexion to pain"),
                            ("2", "Abnormal extension to pain"),
                            ("1", "No motor response"),
                        ],
                        max_length=30,
                    ),
                ),
                ("total_points", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glasgow",
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
