# Generated by Django 5.0 on 2024-02-08 14:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_initial"),
        ("scales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="glasgowcomascale",
            name="hospitalization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="department.hospitalization",
            ),
        ),
        migrations.AlterField(
            model_name="newsscale",
            name="hospitalization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="department.hospitalization",
            ),
        ),
        migrations.AlterField(
            model_name="newsscale",
            name="temperature",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nortonscale",
            name="hospitalization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="department.hospitalization",
            ),
        ),
        migrations.CreateModel(
            name="PainScale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "pain_comment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pain_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("pain_intepretation", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospitalization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.hospitalization",
                    ),
                ),
            ],
        ),
    ]
