# Generated by Django 5.0 on 2024-02-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scales", "0002_alter_glasgowcomascale_hospitalization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="painscale",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="painscale",
            name="pain_intepretation",
        ),
    ]
