# Generated by Django 5.0 on 2024-02-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scales", "0003_alter_painscale_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painscale",
            name="pain_level",
            field=models.CharField(
                choices=[
                    ("0", 0),
                    ("1", 1),
                    ("2", 2),
                    ("3", 3),
                    ("4", 4),
                    ("5", 5),
                    ("6", 6),
                    ("7", 7),
                    ("8", 8),
                    ("9", 9),
                    ("10", 10),
                ],
                max_length=2,
            ),
        ),
    ]
