# Generated by Django 5.0 on 2024-02-11 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scales", "0005_bodymassindex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymassindex",
            name="bmi",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
