# Generated by Django 5.0 on 2024-02-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scales", "0006_alter_bodymassindex_bmi"),
    ]

    operations = [
        migrations.AddField(
            model_name="painscale",
            name="pain_intepretation",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
