# Generated by Django 5.0 on 2024-02-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scales", "0007_painscale_pain_intepretation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="painscale",
            old_name="pain_intepretation",
            new_name="pain_interpretation",
        ),
    ]
