# Generated by Django 5.0 on 2024-02-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scales", "0008_rename_pain_intepretation_painscale_pain_interpretation"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsscale",
            name="score_interpretation",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
