# Generated by Django 5.0 on 2024-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.CharField(
                choices=[
                    ("nurses", "Nurse"),
                    ("physicians", "Physician"),
                    ("secretaries", "Secretary"),
                    ("admins", "Admin"),
                ],
                max_length=50,
            ),
        ),
    ]
