# Generated by Django 5.0 on 2024-01-23 05:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "is_insured",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=True
                    ),
                ),
                ("insurance", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=255)),
                (
                    "admitted_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("consent", models.CharField(blank=True, max_length=255)),
                ("consent_contact_number", models.CharField(blank=True, max_length=15)),
                ("discharged_on", models.DateTimeField(blank=True, null=True)),
                ("is_discharged", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("admitted", "Admitted"),
                            ("discharged_home", "Discharged home"),
                            (
                                "transferred_facility",
                                "Transferred to different medical facility",
                            ),
                            ("died", "Died"),
                        ],
                        default="admitted",
                        max_length=45,
                    ),
                ),
                ("died_on", models.DateTimeField(blank=True, null=True)),
                (
                    "admitted_by",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("observation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
