# Generated by Django 5.0 on 2024-01-23 06:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientobservation",
            name="observation",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
