# Generated by Django 5.0 on 2024-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_alter_patientobservation_observation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientobservation",
            name="observation",
            field=models.TextField(),
        ),
    ]
