# Generated by Django 5.0 on 2024-01-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_alter_patientobservation_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="additional_symptoms",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="main_symptom",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("admitted", "Admitted"),
                    ("discharged_home", "Discharged home"),
                ],
                default="admitted",
                max_length=45,
            ),
        ),
    ]
