# Generated by Django 5.0 on 2024-02-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
        ("patient", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="hospitalization",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="department.department"
            ),
        ),
        migrations.AddField(
            model_name="hospitalization",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospitalizations",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="hospitalization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="department.hospitalization",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="hospitalization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="department.hospitalization",
            ),
        ),
        migrations.AddField(
            model_name="vitalsigns",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="vitalsigns",
            name="hospitalization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="department.hospitalization",
            ),
        ),
    ]
