# Generated by Django 5.0 on 2024-02-26 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalization",
            name="discharged_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
