# Generated by Django 5.0 on 2024-02-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0003_alter_hospitalization_discharged_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalization",
            name="discharged_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
