# Generated by Django 5.0 on 2024-02-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0003_vitalsigns"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsigns",
            name="hospitalization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.hospitalization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="observation",
            name="hospitalization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="department.hospitalization",
            ),
        ),
    ]
