# Generated by Django 5.0 on 2024-02-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0006_alter_department_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitalization",
            old_name="dicharged_on",
            new_name="discharged_on",
        ),
    ]
